services:
  web:
    build: .
    environment:
      VALKEY_HOST: "${VALKEY_HOST}"
      VALKEY_PORT: "${VALKEY_PORT}"
      DEVEL: "${DEVEL}"
      SECRET_KEY: "${SECRET_KEY}"
      FLASK_DEBUG: "${FLASK_DEBUG}"
      REPO_ORG: "${REPO_ORG}"
      GH_TOKEN: "${GH_TOKEN}"
    command: >
      bash -c "
        pip install -r requirements.txt && \
        flask --app webapp/app run --host=0.0.0.0
        "
    ports:
      - "${PORT}:5000"
    volumes:
      - .:/srv
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "${VALKEY_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  cache:
    driver: local
